SELECT '-0.026'::FIXEDDECIMAL;
SELECT '-0.025'::FIXEDDECIMAL;
SELECT '-0.024'::FIXEDDECIMAL;
SELECT '-0.016'::FIXEDDECIMAL;
SELECT '-0.015'::FIXEDDECIMAL;
SELECT '-0.014'::FIXEDDECIMAL;
SELECT '-0.006'::FIXEDDECIMAL;
SELECT '-0.005'::FIXEDDECIMAL;
SELECT '-0.004'::FIXEDDECIMAL;
SELECT '0.004'::FIXEDDECIMAL;
SELECT '0.005'::FIXEDDECIMAL;
SELECT '0.006'::FIXEDDECIMAL;
SELECT '0.014'::FIXEDDECIMAL;
SELECT '0.015'::FIXEDDECIMAL;
SELECT '0.016'::FIXEDDECIMAL;
SELECT '0.024'::FIXEDDECIMAL;
SELECT '0.025'::FIXEDDECIMAL;
SELECT '0.026'::FIXEDDECIMAL;

SELECT '0.145'::FIXEDDECIMAL;
SELECT '0.1450'::FIXEDDECIMAL;
SELECT '0.14509'::FIXEDDECIMAL;
SELECT '0.1451'::FIXEDDECIMAL;

SELECT '0.145'::numeric::FIXEDDECIMAL;
SELECT '0.1450'::numeric::FIXEDDECIMAL;
SELECT '0.14509'::numeric::FIXEDDECIMAL;
SELECT '0.1451'::numeric::FIXEDDECIMAL;

SELECT CAST('-0.026'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('-0.025'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('-0.024'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('-0.016'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('-0.015'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('-0.014'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('-0.006'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('-0.005'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('-0.004'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('0.004'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('0.005'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('0.006'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('0.014'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('0.015'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('0.016'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('0.024'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('0.025'::FLOAT AS FIXEDDECIMAL);
SELECT CAST('0.026'::FLOAT AS FIXEDDECIMAL);

SELECT CAST('-0.026'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('-0.025'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('-0.024'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('-0.016'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('-0.015'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('-0.014'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('-0.006'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('-0.005'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('-0.004'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('0.004'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('0.005'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('0.006'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('0.014'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('0.015'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('0.016'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('0.024'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('0.025'::FLOAT4 AS FIXEDDECIMAL);
SELECT CAST('0.026'::FLOAT4 AS FIXEDDECIMAL);

SELECT CAST('-0.026'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('-0.025'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('-0.024'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('-0.016'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('-0.015'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('-0.014'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('-0.006'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('-0.005'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('-0.004'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('0.004'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('0.005'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('0.006'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('0.014'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('0.015'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('0.016'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('0.024'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('0.025'::NUMERIC AS FIXEDDECIMAL);
SELECT CAST('0.026'::NUMERIC AS FIXEDDECIMAL);

SELECT CAST('-2.6'::FIXEDDECIMAL AS INT);
SELECT CAST('-2.5'::FIXEDDECIMAL AS INT);
SELECT CAST('-2.4'::FIXEDDECIMAL AS INT);
SELECT CAST('-1.6'::FIXEDDECIMAL AS INT);
SELECT CAST('-1.5'::FIXEDDECIMAL AS INT);
SELECT CAST('-1.4'::FIXEDDECIMAL AS INT);
SELECT CAST('-0.6'::FIXEDDECIMAL AS INT);
SELECT CAST('-0.5'::FIXEDDECIMAL AS INT);
SELECT CAST('-0.4'::FIXEDDECIMAL AS INT);
SELECT CAST('0.4'::FIXEDDECIMAL AS INT);
SELECT CAST('0.5'::FIXEDDECIMAL AS INT);
SELECT CAST('0.6'::FIXEDDECIMAL AS INT);
SELECT CAST('1.4'::FIXEDDECIMAL AS INT);
SELECT CAST('1.5'::FIXEDDECIMAL AS INT);
SELECT CAST('1.6'::FIXEDDECIMAL AS INT);
SELECT CAST('2.4'::FIXEDDECIMAL AS INT);
SELECT CAST('2.5'::FIXEDDECIMAL AS INT);
SELECT CAST('2.6'::FIXEDDECIMAL AS INT);

SELECT CAST('-2.6'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('-2.5'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('-2.4'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('-1.6'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('-1.5'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('-1.4'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('-0.6'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('-0.5'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('-0.4'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('0.4'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('0.5'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('0.6'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('1.4'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('1.5'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('1.6'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('2.4'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('2.5'::FIXEDDECIMAL AS SMALLINT);
SELECT CAST('2.6'::FIXEDDECIMAL AS SMALLINT);

SELECT '-0.26'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '-0.25'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '-0.24'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '-0.16'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '-0.15'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '-0.14'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '-0.06'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '-0.05'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '-0.04'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '0.04'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '0.05'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '0.06'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '0.14'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '0.15'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '0.16'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '0.24'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '0.25'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;
SELECT '0.26'::FIXEDDECIMAL / '10.00'::FIXEDDECIMAL;

SELECT '-0.26'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '-0.25'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '-0.24'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '-0.16'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '-0.15'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '-0.14'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '-0.06'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '-0.05'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '-0.04'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '0.04'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '0.05'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '0.06'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '0.14'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '0.15'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '0.16'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '0.24'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '0.25'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;
SELECT '0.26'::FIXEDDECIMAL * '0.10'::FIXEDDECIMAL;

SELECT '-0.26'::FIXEDDECIMAL / '10'::INT4;
SELECT '-0.25'::FIXEDDECIMAL / '10'::INT4;
SELECT '-0.24'::FIXEDDECIMAL / '10'::INT4;
SELECT '-0.16'::FIXEDDECIMAL / '10'::INT4;
SELECT '-0.15'::FIXEDDECIMAL / '10'::INT4;
SELECT '-0.14'::FIXEDDECIMAL / '10'::INT4;
SELECT '-0.06'::FIXEDDECIMAL / '10'::INT4;
SELECT '-0.05'::FIXEDDECIMAL / '10'::INT4;
SELECT '-0.04'::FIXEDDECIMAL / '10'::INT4;
SELECT '0.04'::FIXEDDECIMAL / '10'::INT4;
SELECT '0.05'::FIXEDDECIMAL / '10'::INT4;
SELECT '0.06'::FIXEDDECIMAL / '10'::INT4;
SELECT '0.14'::FIXEDDECIMAL / '10'::INT4;
SELECT '0.15'::FIXEDDECIMAL / '10'::INT4;
SELECT '0.16'::FIXEDDECIMAL / '10'::INT4;
SELECT '0.24'::FIXEDDECIMAL / '10'::INT4;
SELECT '0.25'::FIXEDDECIMAL / '10'::INT4;
SELECT '0.26'::FIXEDDECIMAL / '10'::INT4;

-- fixeddecimalint4mul and int4fixeddecimalmul do not need rounding.

SELECT '-0.26'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '-0.25'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '-0.24'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '-0.16'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '-0.15'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '-0.14'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '-0.06'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '-0.05'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '-0.04'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '0.04'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '0.05'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '0.06'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '0.14'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '0.15'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '0.16'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '0.24'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '0.25'::FIXEDDECIMAL / '10'::SMALLINT;
SELECT '0.26'::FIXEDDECIMAL / '10'::SMALLINT;

-- fixeddecimalint2mul and int2fixeddecimalmul do not need rounding.

SELECT '-26'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '-25'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '-24'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '-16'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '-15'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '-14'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '-06'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '-05'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '-04'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '04'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '05'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '06'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '14'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '15'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '16'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '24'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '25'::SMALLINT / '1000'::FIXEDDECIMAL;
SELECT '26'::SMALLINT / '1000'::FIXEDDECIMAL;

SELECT '-26'::INT / '1000'::FIXEDDECIMAL;
SELECT '-25'::INT / '1000'::FIXEDDECIMAL;
SELECT '-24'::INT / '1000'::FIXEDDECIMAL;
SELECT '-16'::INT / '1000'::FIXEDDECIMAL;
SELECT '-15'::INT / '1000'::FIXEDDECIMAL;
SELECT '-14'::INT / '1000'::FIXEDDECIMAL;
SELECT '-06'::INT / '1000'::FIXEDDECIMAL;
SELECT '-05'::INT / '1000'::FIXEDDECIMAL;
SELECT '-04'::INT / '1000'::FIXEDDECIMAL;
SELECT '04'::INT / '1000'::FIXEDDECIMAL;
SELECT '05'::INT / '1000'::FIXEDDECIMAL;
SELECT '06'::INT / '1000'::FIXEDDECIMAL;
SELECT '14'::INT / '1000'::FIXEDDECIMAL;
SELECT '15'::INT / '1000'::FIXEDDECIMAL;
SELECT '16'::INT / '1000'::FIXEDDECIMAL;
SELECT '24'::INT / '1000'::FIXEDDECIMAL;
SELECT '25'::INT / '1000'::FIXEDDECIMAL;
SELECT '26'::INT / '1000'::FIXEDDECIMAL;

SELECT (54::fixeddecimal / 0.03::fixeddecimal) / 54::fixeddecimal * 0.03::fixeddecimal AS "Should be 1";

WITH sums AS (
        SELECT  SUM(dividend / divisor) AS most_precise,
                --SUM(round_half_even(dividend / divisor, 2)) AS half_even_rounding,
                SUM(dividend::fixeddecimal / divisor::fixeddecimal) AS fixeddecimal_rounding,
                SUM( trunc(dividend / divisor, 2) ) AS trunc_rounding,
                SUM( (dividend / divisor)::numeric(5,2) ) AS numeric_rounding
        FROM    generate_series(.00::numeric,2::numeric,.01::numeric) AS dividend,
                generate_series(.01::numeric,2::numeric,.01::numeric) AS divisor
)
SELECT  --most_precise - half_even_rounding AS half_even_error,
        most_precise - fixeddecimal_rounding AS fixeddecimal_error,
        most_precise - trunc_rounding AS trunc_error,
        most_precise - numeric_rounding AS numeric_error
FROM    sums;

-- These should return 0 rows:

/*
SELECT  *,
        round_half_even( dividend/divisor, 2),
        dividend::fixeddecimal / divisor::fixeddecimal
FROM    generate_series(0::numeric, 100::numeric, 1::numeric) AS dividend,
        generate_series(1::numeric, 100::numeric, 1::numeric) AS divisor
WHERE   round_half_even( dividend/divisor, 2) !=
        dividend::fixeddecimal / divisor::fixeddecimal;

SELECT  *,
        round_half_even( dividend/divisor, 2),
        dividend::fixeddecimal / divisor::fixeddecimal
FROM    generate_series(.00::numeric, 2::numeric, .01::numeric) AS dividend,
        generate_series(.01::numeric, 2::numeric, .01::numeric) AS divisor
WHERE   round_half_even( dividend/divisor, 2) !=
        dividend::fixeddecimal / divisor::fixeddecimal;
*/
